### ISSUE TITLE
Hook Google Analytics?

### ISSUE THREAD

**Issue by diegopamio** [alan2207/react-multistep-wizard#2]
I'd like to know if you have any approach if I want to use `react-ga` to send a page view or event to GA on each wizard step change without the need to control the whole wizard myself.

**Comment by alan2207** [comment]
Not at this point. However it would be a nice feature if there is a use case for it. 

Something like onChange callback could be implemented on the Wizard component and it would get fired every time the Wizard state updates. Let me know if it would solve your problem.
